### ISSUE TITLE
Métodos innecesarios

### ISSUE THREAD

**Issue by josibuttazzoni** [martinamattioli/BarrileteCosmico-UltimaEntrega#1]
https://github.com/martinamattioli/BarrileteCosmico-2da-Entrega/blob/5b2fbfbe16d3f09b60e4c7bc7c69689333f2b19c/BarrileteCosmico/src/localidad.wlk#L17

https://github.com/martinamattioli/BarrileteCosmico-2da-Entrega/blob/5b2fbfbe16d3f09b60e4c7bc7c69689333f2b19c/BarrileteCosmico/src/localidad.wlk#L15

¿Están usando en algún lugar estos métodos o podrían borrarlos?

**Comment by martinamattioli** [comment]
Los usamos en los tests de las localidades. Cuenta? jajaja
